# Generated by Django 5.1.9 on 2025-10-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theater_id', models.CharField(max_length=100)),
                ('mm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('circuit_name', models.CharField(max_length=255)),
                ('theater_name', models.CharField(max_length=255)),
                ('theater_address', models.CharField(max_length=255)),
                ('theater_city', models.CharField(max_length=100)),
                ('theater_state', models.CharField(max_length=50)),
                ('theater_zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('dma', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('studio_name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('date_sh', models.DateField()),
                ('time_sh', models.TimeField()),
                ('auditorium', models.CharField(max_length=50)),
                ('screen_format', models.CharField(max_length=50)),
                ('movie_format', models.CharField(max_length=50)),
                ('language_format', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('child', models.DecimalField(decimal_places=2, max_digits=8)),
                ('senior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_seats', models.IntegerField()),
                ('available', models.IntegerField()),
                ('reserved', models.IntegerField()),
                ('checkered', models.IntegerField()),
                ('actual_total_seats', models.IntegerField()),
                ('actual_available', models.IntegerField()),
                ('actual_reserved', models.IntegerField()),
                ('actual_checkered', models.IntegerField()),
                ('before_reserved', models.IntegerField()),
                ('on_reserved', models.IntegerField()),
                ('after_reserved', models.IntegerField()),
                ('seating_type', models.CharField(max_length=50)),
                ('amenities', models.TextField(blank=True)),
                ('ticket_availability', models.BooleanField(default=True)),
                ('is_ticketing', models.BooleanField(default=True)),
                ('source_flag', models.CharField(blank=True, max_length=50)),
                ('last_updates', models.DateTimeField()),
                ('running_date', models.DateField()),
                ('dsr_date_sh', models.DateTimeField(blank=True, null=True)),
                ('dsr_last_updates', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'indexes': [models.Index(fields=['title'], name='movies_title_179e04_idx'), models.Index(fields=['theater_id'], name='movies_theater_a52ea9_idx'), models.Index(fields=['date_sh'], name='movies_date_sh_fc9494_idx'), models.Index(fields=['genre'], name='movies_genre_66f117_idx'), models.Index(fields=['theater_city', 'theater_state'], name='movies_theater_924c87_idx')],
            },
        ),
    ]
