# Generated by Django 5.1.9 on 2025-10-29 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comparativeanalysis_filmperformancesummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDailyPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('release_date', models.DateField(db_index=True)),
                ('date_sh', models.DateField(db_index=True)),
                ('dir_value', models.IntegerField(db_index=True)),
                ('dbr_value', models.IntegerField(blank=True, db_index=True, null=True)),
                ('total_reserved_seats', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_seats', models.IntegerField(default=0)),
                ('dod_revenue_change', models.FloatField(blank=True, null=True)),
                ('dod_reserved_change', models.FloatField(blank=True, null=True)),
                ('cumulative_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cumulative_reserved', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('occupancy_rate', models.FloatField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movie_daily_performance',
                'indexes': [models.Index(fields=['title', 'release_date'], name='movie_daily_title_0cbb31_idx'), models.Index(fields=['title', 'dir_value'], name='movie_daily_title_1d02aa_idx'), models.Index(fields=['title', 'dbr_value'], name='movie_daily_title_13dc3f_idx'), models.Index(fields=['dir_value'], name='movie_daily_dir_val_12fa5d_idx'), models.Index(fields=['date_sh'], name='movie_daily_date_sh_274d0d_idx'), models.Index(fields=['total_revenue'], name='movie_daily_total_r_6458a9_idx')],
                'unique_together': {('title', 'release_date', 'date_sh')},
            },
        ),
        migrations.CreateModel(
            name='MoviePerformanceComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title1', models.CharField(db_index=True, max_length=255)),
                ('title2', models.CharField(db_index=True, max_length=255)),
                ('release_date1', models.DateField()),
                ('release_date2', models.DateField()),
                ('dir_range_start', models.IntegerField()),
                ('dir_range_end', models.IntegerField()),
                ('period_label', models.CharField(max_length=100)),
                ('title1_total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('title2_total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('title1_total_reserved', models.IntegerField(default=0)),
                ('title2_total_reserved', models.IntegerField(default=0)),
                ('revenue_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revenue_difference_percent', models.FloatField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movie_performance_comparison',
                'indexes': [models.Index(fields=['title1', 'title2'], name='movie_perfo_title1_1ee5ad_idx'), models.Index(fields=['period_label'], name='movie_perfo_period__0a2e47_idx')],
            },
        ),
    ]
