# Generated by Django 5.1.9 on 2025-07-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Installation', 'Installation'), ('Maintenance', 'Maintenance'), ('Design', 'Design'), ('Energy Management', 'Energy Management'), ('Quality Control', 'Quality Control'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
